### ISSUE TITLE
Negative integers ?

### ISSUE THREAD

**Issue by theblacktiger59** [johanhelsing/bevy_sparse_grid_2d#3]
I'm having trouble with entities whose positions are in the negative X and/or Y, they aren't in the Aabb_iter results.
Wondering if it has to do with the key being integers (signed one though, should work fine I imagine).
Have you encountered a similar problem?
I'm aware that I could offset my whole world to only have entities on the positive side, but I would rather try to fix the problem first.

**Comment by johanhelsing** [comment]
Pretty sure i intended that to work.

Do you have a minimal test we could add as a test case?

**Comment by johanhelsing** [comment]
The `matches_complex` test in `lib.rs` should cover this. Are you able to modify it so it fails for something you think should be supported?

**Comment by theblacktiger59** [comment]
I think it might have been a problem with my own code. Sorry, Ain't able to test anything at the moment. Also, being a total beginner, it's safe to assume it's my mistake.

**Comment by johanhelsing** [comment]
No problem, and thanks for taking the trouble to report what you thought was an issue
